version: '3.1'

services:

  redis:
      image: "redis:latest"

  web:
    build:
      context: ./
    
    ports:
      - "8880:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    command: >
      bash -c "flask --app new_api run --host=0.0.0.0 --port=3000"
    depends_on:
      - redis
      - worker
    
  worker:
    build:
      context: ./
    image: madefire/chordtest
    command: bash -c "celery -A worker.celery worker"
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - redis